apiVersion: v1
kind: Service
metadata:
  labels:
    app: eks-panel
  name: eks-panel-svc
spec:
  ports:
  - name: 9191
    port: 9191
    protocol: TCP
    targetPort: 9191
  selector:
    app: eks-panel
  type: ClusterIP
status:
  loadBalancer: {}